### ISSUE TITLE
Add analytics configurations

### ISSUE THREAD

**Issue by elrayle** [curationexperts/nurax#403]
### Descriptive summary

This describes how to setup the new Hyrax analytics configuration.  Analytics are temporarily turned off in this PR to avoid exceptions being thrown.

#### How analytics are turned off

Analytics is temporarily turned off by setting `config.analytics = false` in `/config/initializers/hyrax.rb`.

#### Before turning on

The following ENV variables need to be setup for use in `/config/analytics.yml`:

```
analytics:
  google:
    analytics_id: <%= ENV['GOOGLE_ANALYTICS_ID'] %>
    app_name: <%= ENV['GOOGLE_OAUTH_APP_NAME'] %>
    app_version: <%= ENV['GOOGLE_OAUTH_APP_VERSION'] %>
    privkey_path: <%= ENV['GOOGLE_OAUTH_PRIVATE_KEY_PATH'] %>
    privkey_secret: <%= ENV['GOOGLE_OAUTH_PRIVATE_KEY_SECRET'] %>
    client_email: <%= ENV['GOOGLE_OAUTH_CLIENT_EMAIL'] %>
```

#### To turn on

Remove `config.analytics` and `config.google_analytics_id` from `/config/initializers/hyrax.rb` to avoid conflict with new configuration.

Set `ENV['HYRAX_ANALYTICS'] = true` to turn analytics back on.

### Related work

PR #402 update to latest hyrax (includes save default admin set id & new analytics)
